import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Header/Navbar";
import Footer from "./Components/Footer/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets:["latin", "bengali"]
});

export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" data-theme="light" className={`${notoSerifBengali.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col ">
        <header className="container mx-auto">
          <nav>
            <Navbar />
          </nav>
        </header>
        <main className="container mx-auto">{children}</main>
        <footer className="container mx-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
